### ISSUE TITLE
[Non-issue] Sub-groupes

### ISSUE THREAD

**Issue by d0ob** [narokuu/scienceconversion#1]
Hi there ! 

Is it possible to organize the recipes differently in the production window ? 
I think it would be more readable if the new recipes had their own subgroup.
To have two rows : First one for the vanilla science pack, and below, the conversion recipes !

_I really don't know how ambitious it is to implement, but I know that some mods have a setting to choose if a new subgroup should be created to implement the new item, that would be wonderful !_ 
[Flow control comes to my mind right away. https://mods.factorio.com/mod/Flow%20Control]

In any case, thanks for the mod ! 
That's a neat idea, it's a welcome flexibility that can be quite helpful sometimes !

**Comment by narokuu** [comment]
Hi d0ob I am SO SORRY. I had no idea I had a message on here. I will take a look at this and see if its something I can implement. Please forgive me for not seeing this last year.

**Comment by d0ob** [comment]
There is no problem at all !
At the time I learned how to reorganize item inventory myself, I had to because mod after mods I started to be overbloated with items lol

**Comment by narokuu** [comment]
I understand! Thank you for supporting my mod I really appreciate it! ill close this out for now, and don't be afraid to contact me if you need anything, or have any issues!

**Comment by d0ob** [comment]
It's great to see that you would take care of this even so long after ! That's quality customer service right there ! ^^ Hope you the best for next, thanks much !
